# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Loqman Salamatian
email: ls3748@columbia.edu

description: > # this means to ignore newlines until "url:"
    Loqman Salamatian's personal website. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

footer_text: >
keywords: Loqman Salamatian, Columbia University # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
url: https://jay-sarkar.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
# url:  # the base hostname & protocol for your site
# baseurl: /al-folio/ # the subpath of your site, e.g. /blog/
last_updated:   # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: Burdantes # your GitHub user name
gitlab_username: # your GitLab user name
twitter_username: burdantes # your Twitter handle
linkedin_username: loqman-salamatian-20a2377a # your LinkedIn user name
scholar_userid: wfIuIdMAAAAJ # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
dblp_url: # your DBLP profile url
stackoverflow_id: #your stackoverflow id
# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
<<<<<<< HEAD
blog_name: Jay's notes
blog_description: Some notes about ideas I find interesting
=======

blog_name: Loqman Salamatian Personal Website # blog_name will be displayed in your blog page
blog_nav_title: blog # your blog must have a title for it to be displayed in the nav bar
blog_description: Loqman Salamatian's personal website
permalink: /blog/:year/:title/
>>>>>>> parent of b94b4bd (Deleting blog)

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: # al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
# collections:
  #news:
  #  defaults:
  #    layout: post
  #  output: false
  #  permalink: /news/:path/
  #projects:
  #  output: true
  #  permalink: /projects/:path/
  #teaching:
  #  output: true
  #  permalink: /teaching/:path/

#news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes
include: ['_pages']
exclude: ['_posts']
exclude: ['_news']

# Gems
# gems:
plugins:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Sarkar

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
