name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'   # or consider '3.2'
          bundler-cache: true

      - name: Update RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install npm dependencies
        run: |
          npm install -g mermaid.cli

      - name: Configure Git for Deployment
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy Website
        run: |
          yes | bash bin/deploy --verbose --src master --deploy gh-pages